version: '3.7'
services:
    nginx-webserver:
        image: nginx:1.19.5-alpine
        ports:
          - 80:80
        volumes:
          - ./nginx/html:/usr/share/nginx/html
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        #   - /etc/localtime:/etc/localtime:ro
        #   - /etc/timezone:/etc/timezone:ro

